//Categories
export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

//Locations
export const ADD_LOCATION = 'ADD_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const DELETE_ALL_FROM_CATEGORY = 'DELETE_ALL_FROM_CATEGORY';
export const EDIT_LOCATION = 'EDIT_LOCATION';
export const UPDATE_LOCATIONS = 'UPDATE_LOCATIONS';

// Map
export const CHANGE_MAP_LOCATION = 'CHANGE_MAP_LOCATION';


