//Categories
export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

//Locations
export const ADD_LOCATION = 'ADD_LOCATION';
export const ADD_NEW_LOCATION = 'ADD_NEW_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const DELETE_ALL_FROM_CATEGORY = 'DELETE_ALL_FROM_CATEGORY';
export const EDIT_LOCATION = 'EDIT_LOCATION';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const SET_CHOSEN_ITEM = 'SET_CHOSEN_ITEM';
export const SET_ADD_AND_EDIT_MODE = 'SET_ADD_AND_EDIT_MODE';
export const SET_ADD_MODE = 'SET_ADD_MODE';

// Map
export const CHANGE_MAP_LOCATION = 'CHANGE_MAP_LOCATION';